/**
 * Real code from Karrio (apps/customer/lib/geo.ts), lightly trimmed, pre-tokenized
 * with VS Code "Dark Modern" syntax colors so the hero editor looks like the real thing.
 */
export const syntax = {
  comment: '#6A9955',
  control: '#C586C0',
  storage: '#569CD6',
  constant: '#4FC1FF',
  property: '#9CDCFE',
  number: '#B5CEA8',
  string: '#CE9178',
  fn: '#DCDCAA',
  type: '#4EC9B0',
  plain: '#CCCCCC',
} as const;

type Token = [text: string, tone: keyof typeof syntax];

export const snippet: Token[][] = [
  [['// Monrovia city centre, fallback for addresses without a pin', 'comment']],
  [
    ['export ', 'control'],
    ['const ', 'storage'],
    ['MONROVIA', 'constant'],
    [' = { ', 'plain'],
    ['lat', 'property'],
    [': ', 'plain'],
    ['6.3156', 'number'],
    [', ', 'plain'],
    ['lng', 'property'],
    [': ', 'plain'],
    ['-10.8074', 'number'],
    [' }', 'plain'],
  ],
  [],
  [['// Nominatim covers Liberian streets and needs no API key.', 'comment']],
  [
    ['export ', 'control'],
    ['async ', 'storage'],
    ['function ', 'storage'],
    ['geocodeAddress', 'fn'],
    ['(', 'plain'],
    ['query', 'property'],
    [': ', 'plain'],
    ['string', 'type'],
    [') {', 'plain'],
  ],
  [
    ['  ', 'plain'],
    ['const ', 'storage'],
    ['url', 'constant'],
    [' =', 'plain'],
  ],
  [['    ', 'plain'], ["'https://nominatim.openstreetmap.org/search'", 'string'], [' +', 'plain']],
  [['    ', 'plain'], ["'?format=jsonv2&limit=1&countrycodes=lr'", 'string'], [' +', 'plain']],
  [
    ['    ', 'plain'],
    ['`&q=', 'string'],
    ['${', 'storage'],
    ['encodeURIComponent', 'fn'],
    ['(', 'plain'],
    ['query', 'property'],
    [')', 'plain'],
    ['}', 'storage'],
    ['`', 'string'],
  ],
  [],
  [
    ['  ', 'plain'],
    ['const ', 'storage'],
    ['res', 'constant'],
    [' = ', 'plain'],
    ['await ', 'control'],
    ['fetch', 'fn'],
    ['(', 'plain'],
    ['url', 'constant'],
    [')', 'plain'],
  ],
  [
    ['  ', 'plain'],
    ['if ', 'control'],
    ['(!', 'plain'],
    ['res', 'constant'],
    ['.', 'plain'],
    ['ok', 'property'],
    [') ', 'plain'],
    ['throw ', 'control'],
    ['new ', 'storage'],
    ['Error', 'type'],
    ['(', 'plain'],
    ['`Geocoder responded ', 'string'],
    ['${', 'storage'],
    ['res', 'constant'],
    ['.', 'plain'],
    ['status', 'property'],
    ['}', 'storage'],
    ['`', 'string'],
    [')', 'plain'],
  ],
];
